# Generated by Django 3.2.5 on 2022-08-16 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationrecord",
            name="body",
        ),
        migrations.AddField(
            model_name="applicationrecord",
            name="vo_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationrecord",
            name="OA_date",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="applicationrecord",
            name="application_link",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="applicationrecord",
            name="job_title",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="applicationrecord",
            name="outcome",
            field=models.TextField(blank=True),
        ),
    ]
