# Generated by Django 3.2.5 on 2022-08-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20220816_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='OA_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
