# Generated by Django 3.2.5 on 2022-08-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0003_alter_applicationrecord_oa_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationrecord",
            name="vo_date",
        ),
        migrations.AddField(
            model_name="applicationrecord",
            name="VO_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
